### ISSUE TITLE
Deezer image dimensions on a-tisket pages are misleading

### ISSUE THREAD

**Issue by tigerman325** [ROpdebee/mb-userscripts#273] opened 2021-12-04 21:45 UTC
I've noticed that the resolution shown on a-tisket for Deezer are different than what the image size is that actually uploads. Many times a-tisket will show 1200x1200 or 1400x1400, but when you click on the import into Deezer it actually uploads a 4000x4000 image.

**Comment by kellnerd** [comment] 2021-12-05 11:59
That's not a bug, the script shows the size of the image which is embedded into the a-tisket page (a-tisket uses a static `1400x1400-0` URL that returns the closest available size, which is either 1400x1400 or 1200x1200). This is not necessarily the highest resolution which ECAU can extract using Image Max URL (IMU is dynamically testing different URLs IIRC).

**Comment by tigerman325** [comment] 2021-12-05 22:51
That makes sense.

**Comment by ROpdebee** [comment] 2022-01-22 12:49
@kellnerd is right. Since IMU does indeed dynamically test different possible URLs, so trying to figure out the maximum image and gettings its dimensions will be relatively slow and expensive. Closing as a wontfix, sorry, but we'll document it in #41 (whenever that gets addressed).

**Closed by ROpdebee** 2022-01-22 12:49 UTC
Labels: wontfix, mb_enhanced_cover_art_uploads
