### ISSUE TITLE
MB: Enhanced cover art uploads, Not Working

### ISSUE THREAD

**Issue by tigerman325** [ROpdebee/mb-userscripts#353] opened 2021-12-31 00:48 UTC
Not sure what's going on, but I get the following error no matter the URL or Store button I click
"Failed to grab images: Cannot read properties of undefined (reading 'filename')"

**Comment by ROpdebee** [comment] 2021-12-31 08:26
Please try updating to v2021.12.30 which should fix this. Closing as a duplicate of #351, please reopen if it still doesn't work on the latest version.

**Closed** 2021-12-31 08:26 UTC
