### ISSUE TITLE
Discogs Artwork Import: Failed to fetch or enqueue images: HTTP error 500

### ISSUE THREAD

**Issue by h9rst** [ROpdebee/mb-userscripts#772] opened 2024-07-06 07:46 UTC
Hi all, im tryin to import Artwork from Discogs and everytime i try it i get the following message:
Failed to fetch or enqueue images: HTTP error 500

Amazon, Bandcamp etc. works. Is there a know problem? Thanks

**Comment by kellnerd** [comment] 2024-07-21 09:47
Which version are you using? I am on 2024.5.1 and importing from Discogs works fine for me.

Can you please give us an example URL where it is failing?

**Comment by h9rst** [comment] 2024-07-21 09:58
> Which version are you using? I am on 2024.5.1 and importing from Discogs works fine for me.
> 
> Can you please give us an example URL where it is failing?

Hi, and thanks for your reply.
Im also using Version 2024.5.1
The problem is not a specific release, its on every release.
Dont know if i should get a popup window for the first time using it like the allow bandcamp, apple etc. But on Discogs i never got that popup, and i get the error "Failed to fetch or enqueue images: HTTP error 500" on every Release. Using latest Chrome, Tampermonkey & Mb scripts.
Just for trying, here is one release:
https://musicbrainz.org/release/c3178f51-72ff-4537-9549-ff3dbce27e4d/cover-art
In the options there is also nothing on Exclued

**Comment by kellnerd** [comment] 2024-07-21 10:18
Hmm, I don't have tried it with Chrome but in Firefox it works with Tampermonkey 5.1.1.
There was a big behind the scenes change in Tampermonkey to use MV3 recently (Chrome version 5.2), so it might be related to that.

**Comment by h9rst** [comment] 2024-07-21 13:52
Ok, i tried it with firefox, fresh install of everything... it works. Thank you for your help, will just wait for an update :)

**Comment by ROpdebee** [comment] 2024-07-27 12:14
I managed to reproduce this on the latest Chrome version with Tampermonkey 5.2.0 and 5.2.1, but only when logged in to a Discogs account. Starting from Tampermonkey 5.2.2, the issue seems to be fixed, so this was likely caused by the `GM_xmlHttpRequest` cookie issue that is said to have been fixed in their changelog.

In short: This appears to be fixed in the latest Tampermonkey versions.

**Closed by ROpdebee** 2024-07-27 12:14 UTC
Labels: mb_enhanced_cover_art_uploads, cannot reproduce
